/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>
/* Header for class com_leo_jniexample_JniJavaClass */

#ifndef _Included_com_leo_jniexample_JniJavaClass
#define _Included_com_leo_jniexample_JniJavaClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_leo_jniexample_JniJavaClass
 * Method:    calculate
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_leo_jniexample_JniJavaClass_calculate
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
